import ReduxProvider from "@/redux/ReduxProvider";
import type { Metadata } from "next";
import { Hanken_Grotesk, Roboto } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});
const hankenGrotesk = Hanken_Grotesk({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-hanken-grotesk",
});

export const metadata: Metadata = {
  title: "B2B",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${roboto.variable} ${hankenGrotesk.variable} antialiased`}
      >
        <ReduxProvider>
          <div>{children}</div>
        </ReduxProvider>
        <Toaster />
      </body>
    </html>
  );
}
